FROM python:3

RUN mkdir /var/static

COPY annotations.py /var/static
COPY controller.py /var/static

RUN sed -i "s|\+release,|\+release\+\"-amd64\",|g" /var/static/controller.py
RUN pip install kubernetes

CMD python /var/static/controller.py